//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoDaddyClient.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/GoDaddyChatService")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IChatInterface")]
    public interface IChatInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatInterface/Register", ReplyAction="http://tempuri.org/IChatInterface/RegisterResponse")]
        string Register(GoDaddyClient.ServiceReference.User username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatInterface/Register", ReplyAction="http://tempuri.org/IChatInterface/RegisterResponse")]
        System.Threading.Tasks.Task<string> RegisterAsync(GoDaddyClient.ServiceReference.User username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatInterface/Login", ReplyAction="http://tempuri.org/IChatInterface/LoginResponse")]
        string Login(GoDaddyClient.ServiceReference.User username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatInterface/Login", ReplyAction="http://tempuri.org/IChatInterface/LoginResponse")]
        System.Threading.Tasks.Task<string> LoginAsync(GoDaddyClient.ServiceReference.User username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChatInterfaceChannel : GoDaddyClient.ServiceReference.IChatInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChatInterfaceClient : System.ServiceModel.ClientBase<GoDaddyClient.ServiceReference.IChatInterface>, GoDaddyClient.ServiceReference.IChatInterface {
        
        public ChatInterfaceClient() {
        }
        
        public ChatInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChatInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChatInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChatInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Register(GoDaddyClient.ServiceReference.User username) {
            return base.Channel.Register(username);
        }
        
        public System.Threading.Tasks.Task<string> RegisterAsync(GoDaddyClient.ServiceReference.User username) {
            return base.Channel.RegisterAsync(username);
        }
        
        public string Login(GoDaddyClient.ServiceReference.User username) {
            return base.Channel.Login(username);
        }
        
        public System.Threading.Tasks.Task<string> LoginAsync(GoDaddyClient.ServiceReference.User username) {
            return base.Channel.LoginAsync(username);
        }
    }
}
